image:
  - Visual Studio 2017

build:
  parallel: true
  verbosity: detailed

configuration:
  - Release

environment:
  # update the vcpkg cache even if build fails
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
      - target: Examples
        CMAKE_FLAGS: -DWITH_GUDHI_EXAMPLE=ON -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF

      - target: UnitaryTests
        CMAKE_FLAGS: -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=ON -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF

      - target: Utilities
        CMAKE_FLAGS: -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=ON -DWITH_GUDHI_PYTHON=OFF

      - target: Python
        CMAKE_FLAGS: -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=ON

cache:
  - c:\Tools\vcpkg\installed
  - '%LOCALAPPDATA%\pip\Cache'

init:
  - echo %target%

install:
  - vcpkg install boost-serialization:x64-windows boost-datetime:x64-windows boost-system:x64-windows boost-filesystem:x64-windows boost-unit_test_framework:x64-windows boost-thread:x64-windows boost-program-options:x64-windows eigen3:x64-windows cgal:x64-windows
  - pip install -U setuptools numpy matplotlib scipy Cython pytest sphinx sphinxcontrib-bibtex

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" %CMAKE_FLAGS% -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target check
