image:
  - Visual Studio 2017

build:
  parallel: true
  verbosity: detailed

configuration:
  - Release

environment:
  # update the vcpkg cache even if build fails
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
#      - target: Examples
#        CMAKE_FLAGS: -DWITH_GUDHI_EXAMPLE=ON -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF
#        PYTHON: "C:\\Python37-x64"
#
#      - target: UnitaryTests
#        CMAKE_FLAGS: -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=ON -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF
#        PYTHON: "C:\\Python37-x64"
#
#      - target: Utilities
#        CMAKE_FLAGS: -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=ON -DWITH_GUDHI_PYTHON=OFF
#        PYTHON: "C:\\Python37-x64"

      - target: Python
        CMAKE_FLAGS: -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=ON
        PYTHON: "C:\\Python37-x64"


cache:
  - c:\Tools\vcpkg\installed
  - '%LOCALAPPDATA%\pip\Cache'

init:
  - echo %target%


install:
  - vcpkg install tbb:x64-windows boost-disjoint-sets:x64-windows boost-serialization:x64-windows boost-date-time:x64-windows boost-system:x64-windows boost-filesystem:x64-windows boost-units:x64-windows boost-thread:x64-windows boost-program-options:x64-windows eigen3:x64-windows cgal:x64-windows
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - if [%target%]==[Python] ( python --version &
                              pip --version &
                              pip install -U pip setuptools numpy matplotlib scipy Cython pytest )

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" %CMAKE_FLAGS% -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - if [%target%]==[Python] (
      cd src/cython &
      python setup.py install &
      MSBuild RUN_TESTS.vcxproj
    ) else (
      MSBuild GUDHIdev.sln /m /p:Configuration=Release /p:Platform=x64 &
      ctest -j 1 -C Release -E diff_files
    )
