# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

strategy:
  maxParallel: 2
  matrix:
    x64-Release:
      buildPlatform: x64
      buildConfiguration: Release
    x64-Debug:
      buildPlatform: x64
      buildConfiguration: Debug

workspace:
  clean: all

steps:
- script: 'vcpkg install eigen3:x64-windows'
  displayName: vcpkg install dependencies

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: python -m pip install --upgrade pip setuptools numpy matplotlib scipy Cython pytest sphinx sphinxcontrib-bibtex
  displayName: 'Install tools'

- task: CMake@1
  displayName: 'CMake'
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '.. -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake"'

- task: MSBuild@1
  displayName: 'Build solution GUDHIdev.sln'
  inputs:
    workingDirectory: 'build'
    solution: 'build/GUDHIdev.sln'
    msbuildArguments: '/m /p:Configuration=$(buildConfiguration) /p:Platform=$(buildPlatform)'

- script: 'ctest -j 1 --interactive-debug-mode 0 --output-on-failure -C $(buildConfiguration) -R "in_memory"'
  workingDirectory: 'build'
  displayName: 'Run Ctest'
