version: 2
jobs:
  examples:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - rm -rf build
      - mkdir -p build 
      - cd build 
      - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=ON -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF -DPython_ADDITIONAL_VERSIONS=3 .. 
      - make all test
      - cd ..
  tests:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - rm -rf build
      - mkdir -p build 
      - cd build 
      - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=ON -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF -DPython_ADDITIONAL_VERSIONS=3 .. 
      - make all test
      - cd ..
  utils:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - rm -rf build
      - mkdir -p build 
      - cd build 
      - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=ON -DWITH_GUDHI_PYTHON=OFF -DPython_ADDITIONAL_VERSIONS=3 .. 
      - make all test
      - cd ..
  python:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - rm -rf build
      - mkdir -p build 
      - cd build 
      - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=ON -DPython_ADDITIONAL_VERSIONS=3 .. 
      - make all test sphinx
      - cd ..
  doxygen:
    docker:
      - image: gudhi/ci_for_gudhi:latest
    steps:
      - rm -rf build
      - mkdir -p build 
      - cd build 
      - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=OFF -DWITH_GUDHI_TEST=OFF -DWITH_GUDHI_UTILITIES=OFF -DWITH_GUDHI_PYTHON=OFF -DPython_ADDITIONAL_VERSIONS=3 .. 
      - make doxygen
      - cd ..
