name: pip build linux

on: [push, pull_request]

jobs:
  build:
    name: build pip wheels
    runs-on: ubuntu-latest
    container: gudhi/pip_for_gudhi
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build wheels for Python 3.8
        run: |
          mkdir build_38
          cd build_38
          cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$PYTHON38/bin/python ..
          cd src/python
          $PYTHON38/bin/python setup.py bdist_wheel
          auditwheel repair dist/*.whl